version: "3.8"

services:
  email:
    image: bytemark/smtp
    restart: always
    environment:
      RELAY_HOST: smtp.example.com
      RELAY_PORT: 587
      RELAY_USERNAME: kama@example.com
      RELAY_PASSWORD: kamapassword