name: build-core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    needs: terraform
    uses: ./.github/workflows/build-base.yml
    with:
      configuration: release
      project_file: KamaVerification.Core/KamaVerification.Core.csproj
      project_test_file: KamaVerification.Tests/KamaVerification.Tests.csproj
      output_path: app/publish

  build_container:
    needs: build
    uses: ./.github/workflows/build-container-base.yml
    with:
      configuration: release
      project_file: KamaVerification.Core/KamaVerification.Core.csproj
      project_test_file: KamaVerification.Tests/KamaVerification.Tests.csproj
      output_path: app/publish
      dockerfile: kama-verification-core.dockerfile
      tag: kama-verification:latest